### ISSUE TITLE
get_cmap is deprecated in matplotlib

### ISSUE THREAD

**Issue by JesseSandberg** [BranniganLab/density_threshold_affinity#22]
In the preliminaries notebook cell 2 we use get_cmap, which is deprecated and shares a scary message with the user

![image](https://github.com/BranniganLab/Polar_Binning_DeltaG/assets/22152851/7389ce8c-5875-450b-8081-bb03ebd33ae2)

**Comment by lms464** [comment]
Potential Fix. 

`
from matplotlib import colormaps as cmaps
...
cmaps.get_cmap("xyz")
`
Only accepts a single input, and I encourage adjusting my naming scheme

**Comment by lms464** [comment]
Adjusted cmap command shown above across scripts in notebook and DTA.
